In [1]:
print("Hello World")

Hello World


In [2]:
print(2+3)

5


In [3]:
print("abc" + "def")

abcdef


In [5]:
a = 7
b = 25
def addTwoNum(a,b):
    print(a+b)
addTwoNum(a,b)

32


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
print(np.__version__)

1.21.5


In [8]:
#ndarray is the object array
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
#passing a tuple
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [10]:
#2d arrays 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
#using ndim to check dimensions of an array
a = np.array(3)
b = np.array([2,3])
c = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


In [15]:
#accessing an array using indexing
#0 based indexing
arr = np.array([1,2,3,4,5])
print(arr[4])
print(arr[2] + arr[3])

5
7


In [20]:
#accessing 2D arrays
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[2,2])
print(arr[0,2])
print(arr[2,0])
print(arr[-1,-1]) #1 based negative indexing 
print(arr[3,3])

9
3
7
9


IndexError: index 3 is out of bounds for axis 0 with size 3

In [22]:
#slicing
#includes array start index, but excludes the end index.
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:4])
print(arr[1:7])
print(arr[:5])
print(arr[3:])
print(arr[-4:])
print(arr[:-4])
print(arr[-6:-1])
print(arr[-1:-6])
print(arr[6:1])

[3 4]
[2 3 4 5 6 7]
[1 2 3 4 5]
[4 5 6 7 8 9]
[6 7 8 9]
[1 2 3 4 5]
[4 5 6 7 8]
[]
[]


In [24]:
print(arr[2:7:2]) #step slicing
print(arr[::2]) #alternate position elements
print(arr[1::2])

[3 5 7]
[1 3 5 7 9]
[2 4 6 8]


In [26]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,1:4])
print(arr[0:2,1:4])

[7 8 9]
[[2 3 4]
 [7 8 9]]


In [27]:
#dtype returns the data type of the array
print(arr.dtype)

int32


In [29]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
a.shape

(2, 3)

In [10]:
a.shape = (3,2)
a
#similar to resize : reshape
b = a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
b = a.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
x = np.zeros(3)
x
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [21]:
a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,14])  
c = a*b;  
print(c) 

[ 2  8 18 32 50 72 98]


In [22]:
a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,14,19])  
c = a*b;  
print(c)  

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [25]:
a = 10
b = 12
print(bin(a))
print(bin(b))
print(bin((np.bitwise_and(a,b))))
print(np.bitwise_and(a,b))

0b1010
0b1100
0b1000
8


In [27]:
a = 10
b = 12
print(bin(a))
print(bin(b))
print(bin((np.bitwise_or(a,b))))
print(np.bitwise_or(a,b))

0b1010
0b1100
0b1110
14


In [42]:
print(np.char.add(['Hello ', 'Numpy is '],['World!', 'my fav.']))
print(np.char.multiply('Sam ', 3))
print(np.char.center("Numpy", 9, '^'))
print(np.char.capitalize("today is a fun day"))
print(np.char.title("today is a fun day"))
print(np.char.lower("WeLCOME TO NUMPY"))
print(np.char.upper("welcome to numpy"))

['Hello World!' 'Numpy is my fav.']
Sam Sam Sam 
^^Numpy^^
Today is a fun day
Today Is A Fun Day
welcome to numpy
WELCOME TO NUMPY


In [5]:
import numpy as np
print(np.char.split("Welcome to Numpy", sep=' '))
print(np.char.splitlines("Hi \n Welcome to \n Numpy"))
print(np.char.center("Numpy", 9, ' '))
print(np.char.strip("    Numpy    "))
str = "Welcome to Numpy"
print(np.char.replace(str, "Welcome to ", "www."))

['Welcome', 'to', 'Numpy']
['Hi ', ' Welcome to ', ' Numpy']
  Numpy  
Numpy
www.Numpy


In [14]:
#Numpy trigonometric functions
print(np.sin(30*np.pi/180))
print(np.cos(30*np.pi/180))
print(np.tan(30*np.pi/180))
print(np.arcsin(np.sin(30*np.pi/180))) #cosec
print(np.arccos(np.cos(30*np.pi/180))) #sec
print(np.arctan(np.tan(30*np.pi/180))) #cot
#30*np.pi/180
print(np.degrees(np.arcsin(np.sin(30*np.pi/180))))

0.49999999999999994
0.8660254037844387
0.5773502691896257
0.5235987755982988
0.5235987755982987
0.5235987755982988
29.999999999999996


In [3]:
import numpy as np
#numpy.around(num, decimals)  
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.around(arr,2))
print(np.around(arr,-1))
print(np.floor(arr))
print(np.ceil(arr))

[ 12.2   90.23 123.02  23.2 ]
[ 10.  90. 120.  20.]
[ 12.  90. 123.  23.]
[ 13.  91. 124.  24.]


In [11]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])
print(a)
print(np.amax(a))
print(np.amin(a))

print(np.amax(a,0)) #if arg=0 => check columns
print(np.amin(a,0))
print("\n")
print(np.amax(a,1)) #if arg=1 => check rows
print(np.amin(a,1))
print("\n")
print(np.ptp(a,0)) #ptp => peak-to-peak (max-min)
print(np.ptp(a,1))

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]
80
2
[80 43 31]
[ 2 10 10]


[20 80 43]
[ 2 31 10]


[78 33 21]
[18 49 33]


In [13]:
 #mean, median
print(np.median(a,0))
print(np.mean(a,0))

[22. 43. 20.]
[34.66666667 32.         20.33333333]


In [16]:
#numpy.sort(a, axis, kind, order)  
print(np.sort(a))  
print("\n")
print(np.sort(a, 0)) 

[[ 2 10 20]
 [31 43 80]
 [10 22 43]]


[[ 2 10 10]
 [22 43 20]
 [80 43 31]]
